# -*- coding: utf-8 -*-
"""__init__Conv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VB4K6PwhAhd_Ii5YyxkZArvoJFXHMkwx
"""

from .query_processor import QueryProcessor