# -*- coding: utf-8 -*-
"""__init__Models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g2SXVzotdMKHFhh1PDgtCYZhe95mC3l1
"""

from .summarizer import IntelligentSummarizer
from .semantic_search import SemanticSearchEngine